### ISSUE TITLE
Can't login to WordPress after installing plugin

### ISSUE THREAD

**Issue by trevorstinson** [statamic/wordpress-to-statamic-exporter#1]
I installed this plugin last night, and have not performed any other changes or updates to my site. Now when I try to log in, I receive the following error:

`Warning: Cannot modify header information - headers already sent by (output started at /nfs/c07/h05/mnt/173217/domains/betterworlds.net/html/wp-content/plugins/wordpress-to-statamic-exporter-master/export-to-statamic.php:59) in /nfs/c07/h05/mnt/173217/domains/betterworlds.net/html/wp-includes/pluggable.php on line 1210`

I'm not sure what's going on, but wanted to drop a heads up here in case the plugin is breaking WordPress sites.

**Comment by jackmcdade** [comment]
Thanks for the heads up! What version of WP are you running?

**Comment by trevorstinson** [comment]
WordPress 4.8.

I manually disabled the plugin, then logged in and reactivated it again from the control panel. It gave this error message upon activation (which it probably did the first time as well): `The plugin generated 2 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.`

**Comment by trevorstinson** [comment]
Still present on WordPress 4.9.4 with no other plugins activated.

**Comment by edalzell** [comment]
hey @trevorstinson, it's been updated, are you able to try again?

**Comment by jaggy** [comment]
May we also know the PHP version and server you're using? Thanks! @trevorstinson

**Comment by trevorstinson** [comment]
@edalzell It's working now!

@jaggy PHP 5.6.21 FastCGI on Apache 2.2.22. (I'm not 100% on the Apache version number; not sure if I have a way to check on the MediaTemple account I'm migrating away from, but that's what their accounts page says. I did check the PHP version directly and know it's correct.)
