### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by rosswintle** [statamic/wordpress-to-statamic-exporter#10]
Trivial but important.

The plugin doesn't have a licence so I think, by default, it's copyrighted to you and people aren't allowed to do much with it.  You should add a licence.

Note: WordPress plugin licences should be GPL2 compatible.

**Comment by jackmcdade** [comment]
Done.

**Comment by rosswintle** [comment]
Looks like you added it on a branch but didn't merge?

(P.S. Sorry to nag you with all the issues and PR's today - have been doing some groundwork and wanted this to be working as best it could be!)

**Comment by jackmcdade** [comment]
Nice catch, woops!
