### ISSUE TITLE
Export fails on custom post type

### ISSUE THREAD

**Issue by paptito** [statamic/wordpress-to-statamic-exporter#19]
I'm using the plugin on my local Valet development setup, php7.2, when i choose to export the custom post type 'products' i'm getting a "502 bad gateway" as response. All other exports are working fine.

I tried the plugin on the production site(php5.6) and got the following error:
`Warning: Invalid argument supplied for foreach() in /.../functions.php on line 3113`
Followed by the custom post type export formated in html.

**Comment by icemancast** [comment]
Same result.

**Comment by designvoid** [comment]
Same - was really excited to finally make the move to Statamic v3 but fell over at first hurdle.

**Comment by jasonvarga** [comment]
We don't have a file named `functions.php` so this makes me think it's a Wordpress issue.
Excuse the delay. Closing this issue since it's so old. Feel free to re-open an issue and include the actual path the file so we can know where to look.
